version: '3.8'

services:
  php:
    build: .
    container_name: php_app
    networks:
      - red_app
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=my_database

db:
  image: mariadb:latest
  container_name: mariadb
  networks:
    - red_app
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_DATABASE=my_database
  volumes:
    - db_data:/var/lib/mysql
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql


networks:
  red_app:

volumes:
  db_data:
