# Dockerfile para aplicación PHP

# Imagen base: PHP 7.4 con Apache
FROM php:7.4-apache

# Establecer la variable de entorno para la aplicación
ENV APP_HOME /var/www/html

# Copiar el código de la aplicación en el contenedor
COPY . $APP_HOME

# Exponer el puerto 80 para acceso a la aplicación
EXPOSE 80

# Instalar la extensión mysqli
RUN docker-php-ext-install mysqli

# Copiar el archivo init.sql en el contenedor
COPY init.sql /docker-entrypoint-initdb.d/

# Comando para ejecutar la aplicación
CMD ["apache2-foreground"]